/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */



// Type-only representation of your API routes
export type APIRouter = {

};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [] as const;
